FROM alpine:latest as base

RUN mkdir /home/bot/ 
WORKDIR /home/bot/

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN python3 -m pip install discord.py pytz mysql-connector-python

RUN apk add git

COPY startup.sh /home/bot/
RUN chmod 001 /home/bot/startup.sh

# ENTRYPOINT /home/bot/startup.sh